name: Deploy to Glitch
on:
  push:
    branches:
      - 'master'
jobs:
  # deploys the current repo to glitch
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Deploy this repo to Glitch.com
      - name: Deploy to Glitch
        uses: glitch-tools/sync-glitch-github-action@master
        env:
          GLITCH_PROJECT_ID: ${{ secrets.GLITCH_PROJECT_ID }}
          GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}