name: PR Checks
on: [pull_request]

jobs:
    run_tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2-beta
              with:
                  node-version: ${{ matrix.node-version }}
            - name: unit_test
              run: |
                  yarn
                  yarn test
                  yarn build